name: PlatformIO CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run -e d1_mini

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: .pio/build/d1_mini/WirelessPalaControl.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
